import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import { AIProvider } from "~/context/AIContext";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Chat With YouTube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <AIProvider>
        <Component {...pageProps} />
      </AIProvider>
    </>
  );
};

export default MyApp;
